# Site settings
title: Thomas Chou
email: thomaschou861205@gmail.com
url: https://thomas861205.github.io
description: "An unproductive programmer."
keywords: "Python, C/C++"
skills: "EE X CS X MATH"
meta_author: Thomas Chou

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "0,0,0" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/thomas861205
  - title: facebook
    url: https://www.facebook.com/thomas.chou.3950
  - title: github
    url: https://github.com/thomas861205

# Postal address (add as many lines as necessary)
address:
  - line: Taipei, Taiwan
  - line: Hsinchu, Taiwan 

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
